<?php

declare(strict_types=1);

/**
 * Curated bilingual (fa/en) descriptions for common MTProto methods.
 *
 * Keys are "<namespace>.<method>". Methods not listed here fall back to an
 * auto-generated description in tools/gen_docs.php. Edit this file to improve
 * wording, then re-run: php tools/gen_docs.php
 */
return [
    // ---------------------------------------------------------------- auth
    'auth.sendCode' => ['fa' => 'کد ورود را با پیامک یا اپ درخواست می‌کند.', 'en' => 'Request a login code via SMS or the app.'],
    'auth.signIn' => ['fa' => 'با شماره و کد دریافتی وارد می‌شود.', 'en' => 'Sign in with the phone number and received code.'],
    'auth.signUp' => ['fa' => 'ثبت‌نام کاربر جدید با نام و نام خانوادگی.', 'en' => 'Register a new user with first and last name.'],
    'auth.logOut' => ['fa' => 'از حساب خارج و سشن فعلی را باطل می‌کند.', 'en' => 'Log out and invalidate the current session.'],
    'auth.checkPassword' => ['fa' => 'رمز 2FA را از طریق SRP بررسی و لاگین را کامل می‌کند.', 'en' => 'Verify the 2FA password via SRP and complete login.'],
    'auth.exportAuthorization' => ['fa' => 'مجوز لاگین را برای انتقال به DC دیگر خروجی می‌گیرد.', 'en' => 'Export the login authorization to transfer to another DC.'],
    'auth.importAuthorization' => ['fa' => 'مجوز لاگینِ خروجی‌گرفته‌شده را روی این DC فعال می‌کند.', 'en' => 'Activate an exported login authorization on this DC.'],
    'auth.resetAuthorizations' => ['fa' => 'همه‌ی سشن‌های دیگر را از کار می‌اندازد.', 'en' => 'Invalidate all other sessions.'],
    'auth.recoverPassword' => ['fa' => 'رمز 2FA را با کد بازیابی بازنشانی می‌کند.', 'en' => 'Reset the 2FA password using a recovery code.'],
    'auth.requestPasswordRecovery' => ['fa' => 'کد بازیابی رمز را از طریق ایمیل درخواست می‌کند.', 'en' => 'Request a password recovery code via email.'],
    'auth.resendCode' => ['fa' => 'کد ورود را دوباره ارسال می‌کند.', 'en' => 'Resend the login code.'],
    'auth.cancelCode' => ['fa' => 'کد ورود ارسال‌شده را لغو می‌کند.', 'en' => 'Cancel the sent login code.'],
    'auth.importBotAuthorization' => ['fa' => 'با توکن ربات وارد می‌شود.', 'en' => 'Log in using a bot token.'],
    'auth.bindTempAuthKey' => ['fa' => 'کلید موقت auth را به کلید دائمی می‌چسباند.', 'en' => 'Bind a temporary auth key to the permanent one.'],
    'auth.exportLoginToken' => ['fa' => 'توکن ورود برای دستگاه دیگر می‌سازد.', 'en' => 'Create a login token for another device.'],
    'auth.importLoginToken' => ['fa' => 'با توکن ورودِ دریافتی وارد می‌شود.', 'en' => 'Log in using a received login token.'],
    'auth.acceptLoginToken' => ['fa' => 'درخواست ورود توکنی را تأیید می‌کند.', 'en' => 'Accept a token-based login request.'],

    // -------------------------------------------------------------- account
    'account.registerDevice' => ['fa' => 'دستگاه را برای دریافت push ثبت می‌کند.', 'en' => 'Register a device for push notifications.'],
    'account.unregisterDevice' => ['fa' => 'ثبت دستگاه را برای push حذف می‌کند.', 'en' => 'Unregister a device from push notifications.'],
    'account.updateProfile' => ['fa' => 'نام، نام خانوادگی و درباره‌ی پروفایل را به‌روزرسانی می‌کند.', 'en' => 'Update profile first name, last name and bio.'],
    'account.updateStatus' => ['fa' => 'وضعیت آنلاین/آفلاین را تنظیم می‌کند.', 'en' => 'Set the online/offline status.'],
    'account.updateUsername' => ['fa' => 'نام کاربری (username) را عوض می‌کند.', 'en' => 'Change the username.'],
    'account.updateNotifySettings' => ['fa' => 'تنظیمات اعلان یک peer را تغییر می‌دهد.', 'en' => 'Change notification settings for a peer.'],
    'account.getNotifySettings' => ['fa' => 'تنظیمات اعلان یک peer را می‌خواند.', 'en' => 'Read notification settings for a peer.'],
    'account.getPrivacy' => ['fa' => 'قوانین حریم خصوصی یک کلید را می‌خواند.', 'en' => 'Read the privacy rules for a key.'],
    'account.setPrivacy' => ['fa' => 'قوانین حریم خصوصی را تنظیم می‌کند.', 'en' => 'Set privacy rules.'],
    'account.getWallPapers' => ['fa' => 'فهرست والپیپرها را می‌گیرد.', 'en' => 'Get the list of wallpapers.'],
    'account.uploadWallPaper' => ['fa' => 'یک والپیپر جدید آپلود می‌کند.', 'en' => 'Upload a new wallpaper.'],
    'account.installWallPaper' => ['fa' => 'یک والپیپر را نصب می‌کند.', 'en' => 'Install a wallpaper.'],
    'account.getAccountTTL' => ['fa' => 'مهلت حذف خودکار حساب را می‌خواند.', 'en' => 'Read the account auto-delete TTL.'],
    'account.setAccountTTL' => ['fa' => 'مهلت حذف خودکار حساب را تنظیم می‌کند.', 'en' => 'Set the account auto-delete TTL.'],
    'account.getAuthorizations' => ['fa' => 'فهرست سشن‌های فعال را می‌گیرد.', 'en' => 'List the active sessions.'],
    'account.resetAuthorization' => ['fa' => 'یک سشن خاص را قطع می‌کند.', 'en' => 'Terminate a specific session.'],
    'account.updateDeviceLocked' => ['fa' => 'مدت قفل خودکار دستگاه را تنظیم می‌کند.', 'en' => 'Set the auto-lock period.'],
    'account.deleteAccount' => ['fa' => 'حساب را برای همیشه حذف می‌کند.', 'en' => 'Permanently delete the account.'],
    'account.changePhone' => ['fa' => 'شماره تلفن را عوض می‌کند.', 'en' => 'Change the phone number.'],
    'account.getPassword' => ['fa' => 'تنظیمات رمز 2FA را می‌خواند.', 'en' => 'Read the 2FA password settings.'],
    'account.updatePasswordSettings' => ['fa' => 'رمز 2FA را تنظیم یا عوض می‌کند.', 'en' => 'Set or change the 2FA password.'],
    'account.reportPeer' => ['fa' => 'یک peer را گزارش می‌کند.', 'en' => 'Report a peer.'],
    'account.updateEmojiStatus' => ['fa' => 'وضعیت ایموجی پروفایل را عوض می‌کند.', 'en' => 'Change the profile emoji status.'],
    'account.updateColor' => ['fa' => 'رنگ پروفایل را تغییر می‌دهد.', 'en' => 'Change the profile color.'],
    'account.updateBirthday' => ['fa' => 'تاریخ تولد را ثبت می‌کند.', 'en' => 'Set the birthday.'],
    'account.getContentSettings' => ['fa' => 'تنظیمات محتوای حساس را می‌خواند.', 'en' => 'Read sensitive-content settings.'],
    'account.setContentSettings' => ['fa' => 'تنظیمات محتوای حساس را تغییر می‌دهد.', 'en' => 'Set sensitive-content settings.'],
    'account.setAccountTTL' => ['fa' => 'مهلت حذف خودکار حساب را تنظیم می‌کند.', 'en' => 'Set the account auto-delete TTL.'],
    'account.getTmpPassword' => ['fa' => 'رمز موقت برای sessionهای محدود می‌سازد.', 'en' => 'Create a temporary password for restricted sessions.'],

    // -------------------------------------------------------------- messages
    'messages.sendMessage' => ['fa' => 'یک پیام متنی می‌فرستد.', 'en' => 'Send a text message.'],
    'messages.sendMedia' => ['fa' => 'پیامی با رسانه (عکس/فایل/…) می‌فرستد.', 'en' => 'Send a message with media.'],
    'messages.sendMultiMedia' => ['fa' => 'چند رسانه را در یک پیام (آلبوم) می‌فرستد.', 'en' => 'Send multiple media in one message (album).'],
    'messages.editMessage' => ['fa' => 'پیام را ویرایش می‌کند.', 'en' => 'Edit a message.'],
    'messages.deleteMessages' => ['fa' => 'پیام‌ها را حذف می‌کند.', 'en' => 'Delete messages.'],
    'messages.forwardMessages' => ['fa' => 'پیام‌ها را فوروارد می‌کند.', 'en' => 'Forward messages.'],
    'messages.getHistory' => ['fa' => 'تاریخچه‌ی پیام‌های یک گفتگو را می‌گیرد.', 'en' => 'Get the message history of a chat.'],
    'messages.getDialogs' => ['fa' => 'فهرست گفتگوهای اخیر را می‌گیرد.', 'en' => 'Get the list of recent dialogs.'],
    'messages.getMessages' => ['fa' => 'پیام‌ها را با شناسه می‌گیرد.', 'en' => 'Get messages by id.'],
    'messages.search' => ['fa' => 'در پیام‌های یک گفتگو جستجو می‌کند.', 'en' => 'Search messages within a chat.'],
    'messages.searchGlobal' => ['fa' => 'در همه‌ی گفتگوها جستجو می‌کند.', 'en' => 'Search across all dialogs.'],
    'messages.setTyping' => ['fa' => 'وضعیت در حال تایپ را می‌فرستد.', 'en' => 'Send a typing status.'],
    'messages.readHistory' => ['fa' => 'پیام‌های یک گفتگو را خوانده‌شده می‌کند.', 'en' => 'Mark a chat as read.'],
    'messages.readMentions' => ['fa' => 'منشن‌ها را خوانده‌شده می‌کند.', 'en' => 'Mark mentions as read.'],
    'messages.readMessageContents' => ['fa' => 'محتوای پیام‌ها را خوانده‌شده می‌کند.', 'en' => 'Mark message contents as read.'],
    'messages.getReplies' => ['fa' => 'ریپلای‌های یک پیام را می‌گیرد.', 'en' => 'Get replies to a message.'],
    'messages.getDiscussionMessage' => ['fa' => 'پیام بحثِ مرتبط با یک پست کانال را می‌گیرد.', 'en' => 'Get the discussion message of a channel post.'],
    'messages.getMessagesViews' => ['fa' => 'تعداد بازدید پیام‌ها را می‌گیرد.', 'en' => 'Get message view counts.'],
    'messages.getWebPage' => ['fa' => 'پیش‌نمایش یک لینک را می‌گیرد.', 'en' => 'Get the preview of a link.'],
    'messages.getPeerDialogs' => ['fa' => 'گفتگوهای یک peer خاص را می‌گیرد.', 'en' => 'Get dialogs for specific peers.'],
    'messages.getPeerSettings' => ['fa' => 'تنظیمات یک peer را می‌خواند.', 'en' => 'Read the settings of a peer.'],
    'messages.getPinnedDialogs' => ['fa' => 'گفتگوهای سنجاق‌شده را می‌گیرد.', 'en' => 'Get pinned dialogs.'],
    'messages.updatePinnedMessage' => ['fa' => 'یک پیام را سنجاق یا از سنجاق برمی‌دارد.', 'en' => 'Pin or unpin a message.'],
    'messages.unpinAllMessages' => ['fa' => 'سنجاق همه‌ی پیام‌ها را برمی‌دارد.', 'en' => 'Unpin all messages.'],
    'messages.getChats' => ['fa' => 'گفتگوها را با شناسه می‌گیرد.', 'en' => 'Get chats by id.'],
    'messages.getFullChat' => ['fa' => 'اطلاعات کامل یک گفتگو را می‌گیرد.', 'en' => 'Get full chat info.'],
    'messages.createChat' => ['fa' => 'یک گروه جدید می‌سازد.', 'en' => 'Create a new group.'],
    'messages.deleteChat' => ['fa' => 'یک گروه را حذف می‌کند.', 'en' => 'Delete a group.'],
    'messages.addChatUser' => ['fa' => 'کاربری را به گروه اضافه می‌کند.', 'en' => 'Add a user to a group.'],
    'messages.deleteChatUser' => ['fa' => 'کاربری را از گروه حذف می‌کند.', 'en' => 'Remove a user from a group.'],
    'messages.editChatTitle' => ['fa' => 'عنوان گروه را عوض می‌کند.', 'en' => 'Change the group title.'],
    'messages.editChatPhoto' => ['fa' => 'عکس گروه را عوض می‌کند.', 'en' => 'Change the group photo.'],
    'messages.editChatAdmin' => ['fa' => 'دسترسی ادمین یک کاربر را تغییر می‌دهد.', 'en' => 'Change a user\'s admin rights.'],
    'messages.editChatAbout' => ['fa' => 'درباره‌ی گروه را عوض می‌کند.', 'en' => 'Change the group description.'],
    'messages.migrateChat' => ['fa' => 'گروه را به سوپرگروه تبدیل می‌کند.', 'en' => 'Migrate a group to a supergroup.'],
    'messages.sendReaction' => ['fa' => 'ری‌اکشن روی پیام می‌گذارد.', 'en' => 'React to a message.'],
    'messages.getMessageReactionsList' => ['fa' => 'فهرست ری‌اکشن‌های یک پیام را می‌گیرد.', 'en' => 'List the reactions on a message.'],
    'messages.sendVote' => ['fa' => 'به یک نظرسنجی رأی می‌دهد.', 'en' => 'Vote in a poll.'],
    'messages.getPollResults' => ['fa' => 'نتایج نظرسنجی را می‌گیرد.', 'en' => 'Get poll results.'],
    'messages.getPollVotes' => ['fa' => 'آرای یک گزینه‌ی نظرسنجی را می‌گیرد.', 'en' => 'Get the votes for a poll option.'],
    'messages.getScheduledMessages' => ['fa' => 'پیام‌های زمان‌بندی‌شده را می‌گیرد.', 'en' => 'Get scheduled messages.'],
    'messages.sendScheduledMessages' => ['fa' => 'پیام‌های زمان‌بندی‌شده را فوراً می‌فرستد.', 'en' => 'Send scheduled messages now.'],
    'messages.deleteScheduledMessages' => ['fa' => 'پیام‌های زمان‌بندی‌شده را حذف می‌کند.', 'en' => 'Delete scheduled messages.'],
    'messages.saveDraft' => ['fa' => 'پیش‌نویس پیام را ذخیره می‌کند.', 'en' => 'Save a message draft.'],
    'messages.getAllDrafts' => ['fa' => 'همه‌ی پیش‌نویس‌ها را می‌گیرد.', 'en' => 'Get all drafts.'],
    'messages.clearAllDrafts' => ['fa' => 'همه‌ی پیش‌نویس‌ها را پاک می‌کند.', 'en' => 'Clear all drafts.'],
    'messages.checkChatInvite' => ['fa' => 'یک لینک دعوت را بررسی می‌کند.', 'en' => 'Check a chat invite link.'],
    'messages.importChatInvite' => ['fa' => 'با لینک دعوت عضو می‌شود.', 'en' => 'Join via an invite link.'],
    'messages.exportChatInvite' => ['fa' => 'لینک دعوت می‌سازد.', 'en' => 'Create an invite link.'],
    'messages.getInlineBotResults' => ['fa' => 'نتایج یک کوئری inline از ربات می‌گیرد.', 'en' => 'Get inline results from a bot.'],
    'messages.getStickerSet' => ['fa' => 'یک بسته‌ی استیکر را می‌گیرد.', 'en' => 'Get a sticker set.'],
    'messages.getRecentStickers' => ['fa' => 'استیکرهای اخیر را می‌گیرد.', 'en' => 'Get recent stickers.'],
    'messages.installStickerSet' => ['fa' => 'یک بسته‌ی استیکر را نصب می‌کند.', 'en' => 'Install a sticker set.'],
    'messages.uninstallStickerSet' => ['fa' => 'یک بسته‌ی استیکر را حذف می‌کند.', 'en' => 'Uninstall a sticker set.'],
    'messages.getSavedGifs' => ['fa' => 'گیف‌های ذخیره‌شده را می‌گیرد.', 'en' => 'Get saved GIFs.'],
    'messages.saveGif' => ['fa' => 'یک گیف را ذخیره می‌کند.', 'en' => 'Save a GIF.'],
    'messages.setGameScore' => ['fa' => 'امتیاز یک بازی را ثبت می‌کند.', 'en' => 'Set the score of a game.'],
    'messages.getGameHighScores' => ['fa' => 'بهترین امتیازهای یک بازی را می‌گیرد.', 'en' => 'Get the high scores of a game.'],
    'messages.getOnlines' => ['fa' => 'کاربران آنلاین را می‌گیرد.', 'en' => 'Get online users.'],
    'messages.getCommonChats' => ['fa' => 'گفتگوهای مشترک با یک کاربر را می‌گیرد.', 'en' => 'Get chats in common with a user.'],
    'messages.getForumTopics' => ['fa' => 'موضوعات (topic) یک فروم را می‌گیرد.', 'en' => 'Get the topics of a forum.'],
    'messages.createForumTopic' => ['fa' => 'یک موضوع در فروم می‌سازد.', 'en' => 'Create a forum topic.'],
    'messages.editForumTopic' => ['fa' => 'یک موضوع فروم را ویرایش می‌کند.', 'en' => 'Edit a forum topic.'],
    'messages.report' => ['fa' => 'یک پیام را گزارش می‌کند.', 'en' => 'Report a message.'],
    'messages.reportSpam' => ['fa' => 'یک peer را اسپم گزارش می‌کند.', 'en' => 'Report a peer as spam.'],
    'messages.transcribeAudio' => ['fa' => 'صدای یک پیام را به متن تبدیل می‌کند.', 'en' => 'Transcribe a voice message.'],
    'messages.translateText' => ['fa' => 'متن پیام را ترجمه می‌کند.', 'en' => 'Translate message text.'],
    'messages.getFactCheck' => ['fa' => 'فکت‌چک یک پیام را می‌گیرد.', 'en' => 'Get the fact-check of a message.'],
    'messages.editFactCheck' => ['fa' => 'فکت‌چک یک پیام را ویرایش می‌کند.', 'en' => 'Edit the fact-check of a message.'],
    'messages.setHistoryTTL' => ['fa' => 'مهلت انقضای پیام‌ها را تنظیم می‌کند.', 'en' => 'Set the auto-delete period for messages.'],
    'messages.setDefaultReaction' => ['fa' => 'ری‌اکشن پیش‌فرض را تنظیم می‌کند.', 'en' => 'Set the default reaction.'],
    'messages.getSavedDialogs' => ['fa' => 'گفتگوهای ذخیره‌شده (Saved) را می‌گیرد.', 'en' => 'Get saved dialogs.'],
    'messages.getSavedHistory' => ['fa' => 'تاریخچه‌ی پیام‌های ذخیره‌شده را می‌گیرد.', 'en' => 'Get saved message history.'],
    'messages.getSearchCounters' => ['fa' => 'شمارنده‌ی نتایج جستجو را می‌گیرد.', 'en' => 'Get search result counters.'],
    'messages.getUnreadMentions' => ['fa' => 'منشن‌های خوانده‌نشده را می‌گیرد.', 'en' => 'Get unread mentions.'],
    'messages.markDialogUnread' => ['fa' => 'یک گفتگو را خوانده‌نشده می‌کند.', 'en' => 'Mark a dialog as unread.'],
    'messages.toggleDialogPin' => ['fa' => 'یک گفتگو را سنجاق/از سنجاق برمی‌دارد.', 'en' => 'Pin or unpin a dialog.'],
    'messages.reorderPinnedDialogs' => ['fa' => 'ترتیب گفتگوهای سنجاق‌شده را عوض می‌کند.', 'en' => 'Reorder pinned dialogs.'],
    'messages.updateDialogFilter' => ['fa' => 'یک پوشه (فیلتر گفتگو) را می‌سازد یا ویرایش می‌کند.', 'en' => 'Create or edit a dialog filter/folder.'],
    'messages.getDialogFilters' => ['fa' => 'پوشه‌های گفتگو را می‌گیرد.', 'en' => 'Get dialog folders.'],
    'messages.requestWebView' => ['fa' => 'یک WebView باز می‌کند.', 'en' => 'Open a WebView.'],
    'messages.getInlineGameHighScores' => ['fa' => 'بهترین امتیازهای بازی inline را می‌گیرد.', 'en' => 'Get inline game high scores.'],

    // -------------------------------------------------------------- contacts
    'contacts.getContacts' => ['fa' => 'فهرست مخاطبین دفترچه را می‌گیرد.', 'en' => 'Get the address-book contacts.'],
    'contacts.addContact' => ['fa' => 'یک مخاطب اضافه می‌کند.', 'en' => 'Add a contact.'],
    'contacts.deleteContacts' => ['fa' => 'مخاطبین را حذف می‌کند.', 'en' => 'Delete contacts.'],
    'contacts.deleteByPhones' => ['fa' => 'مخاطبین را با شماره تلفن حذف می‌کند.', 'en' => 'Delete contacts by phone number.'],
    'contacts.importContacts' => ['fa' => 'مخاطبین را وارد می‌کند.', 'en' => 'Import contacts.'],
    'contacts.block' => ['fa' => 'یک کاربر را بلاک می‌کند.', 'en' => 'Block a user.'],
    'contacts.unblock' => ['fa' => 'یک کاربر را آنبلاک می‌کند.', 'en' => 'Unblock a user.'],
    'contacts.getBlocked' => ['fa' => 'فهرست کاربران بلاک‌شده را می‌گیرد.', 'en' => 'Get the blocked users.'],
    'contacts.search' => ['fa' => 'در مخاطبین جستجو می‌کند.', 'en' => 'Search contacts.'],
    'contacts.resolveUsername' => ['fa' => 'یک username را به peer تبدیل می‌کند.', 'en' => 'Resolve a username to a peer.'],
    'contacts.getStatuses' => ['fa' => 'وضعیت آنلاین مخاطبین را می‌گیرد.', 'en' => 'Get contact online statuses.'],
    'contacts.getTopPeers' => ['fa' => 'پرکاربردترین پییرها را می‌گیرد.', 'en' => 'Get the most-used peers.'],
    'contacts.resetTopPeerRating' => ['fa' => 'رتبه‌ی یک پییر پرکاربرد را صفر می‌کند.', 'en' => 'Reset the rating of a top peer.'],
    'contacts.getLocated' => ['fa' => 'مخاطبین نزدیک را می‌گیرد.', 'en' => 'Get nearby contacts.'],

    // -------------------------------------------------------------- channels
    'channels.createChannel' => ['fa' => 'یک کانال یا سوپرگروه می‌سازد.', 'en' => 'Create a channel or supergroup.'],
    'channels.deleteChannel' => ['fa' => 'یک کانال را حذف می‌کند.', 'en' => 'Delete a channel.'],
    'channels.joinChannel' => ['fa' => 'به یک کانال می‌پیوندد.', 'en' => 'Join a channel.'],
    'channels.leaveChannel' => ['fa' => 'از یک کانال خارج می‌شود.', 'en' => 'Leave a channel.'],
    'channels.editAdmin' => ['fa' => 'دسترسی ادمین یک کاربر را تغییر می‌دهد.', 'en' => 'Change a user\'s admin rights.'],
    'channels.editBanned' => ['fa' => 'محدودیت‌ها یا بن کاربر را تغییر می‌دهد.', 'en' => 'Change a user\'s restrictions or ban.'],
    'channels.editPhoto' => ['fa' => 'عکس کانال را عوض می‌کند.', 'en' => 'Change the channel photo.'],
    'channels.editTitle' => ['fa' => 'عنوان کانال را عوض می‌کند.', 'en' => 'Change the channel title.'],
    'channels.editLocation' => ['fa' => 'موقعیت مکانی کانال را تغییر می‌دهد.', 'en' => 'Change the channel location.'],
    'channels.updateUsername' => ['fa' => 'نام کاربری کانال را عوض می‌کند.', 'en' => 'Change the channel username.'],
    'channels.toggleSignatures' => ['fa' => 'نمایش امضای نویسنده را روشن/خاموش می‌کند.', 'en' => 'Toggle author signatures.'],
    'channels.toggleSlowMode' => ['fa' => 'حالت آهسته (slow mode) را تنظیم می‌کند.', 'en' => 'Toggle slow mode.'],
    'channels.toggleForum' => ['fa' => 'حالت فروم را روشن/خاموش می‌کند.', 'en' => 'Toggle forum mode.'],
    'channels.toggleJoinRequest' => ['fa' => 'درخواست عضویت را روشن/خاموش می‌کند.', 'en' => 'Toggle join requests.'],
    'channels.setStickers' => ['fa' => 'استیکرهای مجاز کانال را تنظیم می‌کند.', 'en' => 'Set the allowed channel stickers.'],
    'channels.setDiscussionGroup' => ['fa' => 'گروه بحث کانال را تنظیم می‌کند.', 'en' => 'Set the channel\'s discussion group.'],
    'channels.getChannels' => ['fa' => 'کانال‌ها را با شناسه می‌گیرد.', 'en' => 'Get channels by id.'],
    'channels.getFullChannel' => ['fa' => 'اطلاعات کامل یک کانال را می‌گیرد.', 'en' => 'Get full channel info.'],
    'channels.getParticipants' => ['fa' => 'اعضای کانال را می‌گیرد.', 'en' => 'Get channel participants.'],
    'channels.getParticipant' => ['fa' => 'یک عضو خاص کانال را می‌گیرد.', 'en' => 'Get a specific channel participant.'],
    'channels.getAdminLog' => ['fa' => 'گزارش رویدادهای مدیریتی کانال را می‌گیرد.', 'en' => 'Get the channel admin log.'],
    'channels.getAdminedPublicChannels' => ['fa' => 'کانال‌های عمومی که ادمین آن هستی را می‌گیرد.', 'en' => 'Get public channels you administer.'],
    'channels.readHistory' => ['fa' => 'پیام‌های کانال را خوانده‌شده می‌کند.', 'en' => 'Mark channel messages as read.'],
    'channels.deleteMessages' => ['fa' => 'پیام‌های کانال را حذف می‌کند.', 'en' => 'Delete channel messages.'],
    'channels.deleteHistory' => ['fa' => 'تاریخچه‌ی کانال را حذف می‌کند.', 'en' => 'Delete channel history.'],
    'channels.exportMessageLink' => ['fa' => 'لینک مستقیم یک پیام کانال را می‌سازد.', 'en' => 'Create a direct link to a channel message.'],
    'channels.reportSpam' => ['fa' => 'یک کانال را اسپم گزارش می‌کند.', 'en' => 'Report a channel as spam.'],
    'channels.convertToGigagroup' => ['fa' => 'سوپرگروه را به gigagroup تبدیل می‌کند.', 'en' => 'Convert a supergroup to a gigagroup.'],
    'channels.inviteToChannel' => ['fa' => 'کاربران را به کانال دعوت می‌کند.', 'en' => 'Invite users to a channel.'],

    // ---------------------------------------------------------------- users
    'users.getUsers' => ['fa' => 'کاربران را با شناسه می‌گیرد.', 'en' => 'Get users by id.'],
    'users.getFullUser' => ['fa' => 'اطلاعات کامل یک کاربر را می‌گیرد.', 'en' => 'Get full user info.'],
    'users.setSecureValueErrors' => ['fa' => 'خطای اعتبارسنجی secure value را گزارش می‌کند.', 'en' => 'Report secure-value validation errors.'],
    'users.getSavedMusic' => ['fa' => 'موسیقی‌های ذخیره‌شده را می‌گیرد.', 'en' => 'Get saved music.'],
    'users.suggestBirthday' => ['fa' => 'تاریخ تولد را پیشنهاد می‌کند.', 'en' => 'Suggest a birthday.'],

    // ---------------------------------------------------------------- upload
    'upload.saveFilePart' => ['fa' => 'یک قطعه از فایل را آپلود می‌کند.', 'en' => 'Upload one chunk of a file.'],
    'upload.saveBigFilePart' => ['fa' => 'یک قطعه از فایل بزرگ را آپلود می‌کند.', 'en' => 'Upload one chunk of a big file.'],
    'upload.getFile' => ['fa' => 'فایل را دانلود می‌کند.', 'en' => 'Download a file.'],
    'upload.getWebFile' => ['fa' => 'فایل وب (آواتار و…) را دانلود می‌کند.', 'en' => 'Download a web file (avatar, etc.).'],
    'upload.getCdnFile' => ['fa' => 'فایل را از CDN دانلود می‌کند.', 'en' => 'Download a file from the CDN.'],
    'upload.reuploadCdnFile' => ['fa' => 'فایل CDN را دوباره آپلود می‌کند.', 'en' => 'Re-upload a CDN file.'],

    // ----------------------------------------------------------------- help
    'help.getConfig' => ['fa' => 'پیکربندی فعلی سرور را می‌گیرد.', 'en' => 'Get the current server configuration.'],
    'help.getNearestDc' => ['fa' => 'نزدیک‌ترین دیتاسنتر را می‌گیرد.', 'en' => 'Get the nearest data center.'],
    'help.getAppConfig' => ['fa' => 'پیکربندی اپ را می‌گیرد.', 'en' => 'Get the app configuration.'],
    'help.getAppUpdate' => ['fa' => 'اطلاعات نسخه‌ی جدید اپ را می‌گیرد.', 'en' => 'Get app update info.'],
    'help.getSupport' => ['fa' => 'اطلاعات پشتیبانی را می‌گیرد.', 'en' => 'Get support info.'],
    'help.getCountriesList' => ['fa' => 'فهرست کشورها را می‌گیرد.', 'en' => 'Get the list of countries.'],
    'help.getInviteText' => ['fa' => 'متن دعوت به تلگرام را می‌گیرد.', 'en' => 'Get the Telegram invite text.'],
    'help.getPassportConfig' => ['fa' => 'پیکربندی پاسپورت را می‌گیرد.', 'en' => 'Get the passport configuration.'],
    'help.getTermsOfServiceUpdate' => ['fa' => 'به‌روزرسانی قوانین استفاده را می‌گیرد.', 'en' => 'Get terms-of-service updates.'],
    'help.getPromoData' => ['fa' => 'داده‌ی تبلیغاتی را می‌گیرد.', 'en' => 'Get promotional data.'],

    // ---------------------------------------------------------------- photos
    'photos.updateProfilePhoto' => ['fa' => 'عکس پروفایل را عوض می‌کند.', 'en' => 'Change the profile photo.'],
    'photos.uploadProfilePhoto' => ['fa' => 'عکس پروفایل را آپلود می‌کند.', 'en' => 'Upload a profile photo.'],
    'photos.uploadContactProfilePhoto' => ['fa' => 'عکس پروفایل برای یک مخاطب آپلود می‌کند.', 'en' => 'Upload a profile photo for a contact.'],
    'photos.deletePhotos' => ['fa' => 'عکس‌ها را حذف می‌کند.', 'en' => 'Delete photos.'],
    'photos.getUserPhotos' => ['fa' => 'عکس‌های پروفایل یک کاربر را می‌گیرد.', 'en' => 'Get a user\'s profile photos.'],

    // ----------------------------------------------------------------- bots
    'bots.getBotInfo' => ['fa' => 'اطلاعات یک ربات را می‌گیرد.', 'en' => 'Get info about a bot.'],
    'bots.setBotInfo' => ['fa' => 'اطلاعات یک ربات را تنظیم می‌کند.', 'en' => 'Set bot info.'],
    'bots.getBotCommands' => ['fa' => 'دستورات یک ربات را می‌گیرد.', 'en' => 'Get a bot\'s commands.'],
    'bots.setBotCommands' => ['fa' => 'دستورات یک ربات را تنظیم می‌کند.', 'en' => 'Set a bot\'s commands.'],
    'bots.resetBotCommands' => ['fa' => 'دستورات ربات را بازنشانی می‌کند.', 'en' => 'Reset a bot\'s commands.'],
    'bots.getBotMenuButton' => ['fa' => 'دکمه‌ی منوی ربات را می‌گیرد.', 'en' => 'Get the bot menu button.'],
    'bots.setBotMenuButton' => ['fa' => 'دکمه‌ی منوی ربات را تنظیم می‌کند.', 'en' => 'Set the bot menu button.'],
    'bots.getAdminedBots' => ['fa' => 'ربات‌هایی که ادمین آن هستی را می‌گیرد.', 'en' => 'Get bots you administer.'],

    // -------------------------------------------------------------- stickers
    'stickers.createStickerSet' => ['fa' => 'یک بسته‌ی استیکر می‌سازد.', 'en' => 'Create a sticker set.'],
    'stickers.addStickerToSet' => ['fa' => 'استیکری به بسته اضافه می‌کند.', 'en' => 'Add a sticker to a set.'],
    'stickers.removeStickerFromSet' => ['fa' => 'استیکری را از بسته حذف می‌کند.', 'en' => 'Remove a sticker from a set.'],
    'stickers.setStickerSetThumb' => ['fa' => 'تصویر بندانگشتی بسته را تنظیم می‌کند.', 'en' => 'Set a sticker set thumbnail.'],
    'stickers.checkShortName' => ['fa' => 'موجودیِ نام کوتاه بسته را بررسی می‌کند.', 'en' => 'Check sticker set short-name availability.'],

    // -------------------------------------------------------------- payments
    'payments.getPaymentForm' => ['fa' => 'فرم پرداخت را می‌گیرد.', 'en' => 'Get the payment form.'],
    'payments.sendPaymentForm' => ['fa' => 'پرداخت را نهایی می‌کند.', 'en' => 'Submit the payment.'],
    'payments.getStarsStatus' => ['fa' => 'وضعیت ستاره‌ها (Stars) را می‌گیرد.', 'en' => 'Get the Stars status.'],
    'payments.getStarsTransactions' => ['fa' => 'تراکنش‌های ستاره را می‌گیرد.', 'en' => 'Get Stars transactions.'],
    'payments.getStarsGiftOptions' => ['fa' => 'گزینه‌های هدیه‌ی ستاره را می‌گیرد.', 'en' => 'Get Stars gift options.'],
    'payments.saveStarGift' => ['fa' => 'یک هدیه‌ی ستاره را ذخیره می‌کند.', 'en' => 'Save a Star gift.'],
    'payments.getSavedStarGifts' => ['fa' => 'هدیه‌های ستاره‌ی ذخیره‌شده را می‌گیرد.', 'en' => 'Get saved Star gifts.'],
    'payments.upgradeStarGift' => ['fa' => 'یک هدیه‌ی ستاره را ارتقا می‌دهد.', 'en' => 'Upgrade a Star gift.'],

    // ----------------------------------------------------------------- phone
    'phone.requestCall' => ['fa' => 'تماس صوتی/تصویری درخواست می‌کند.', 'en' => 'Request a voice/video call.'],
    'phone.acceptCall' => ['fa' => 'تماس را می‌پذیرد.', 'en' => 'Accept a call.'],
    'phone.discardCall' => ['fa' => 'تماس را رد/قطع می‌کند.', 'en' => 'Discard a call.'],
    'phone.createGroupCall' => ['fa' => 'تماس گروهی می‌سازد.', 'en' => 'Create a group call.'],
    'phone.joinGroupCall' => ['fa' => 'به تماس گروهی می‌پیوندد.', 'en' => 'Join a group call.'],
    'phone.leaveGroupCall' => ['fa' => 'از تماس گروهی خارج می‌شود.', 'en' => 'Leave a group call.'],
    'phone.editGroupCallParticipant' => ['fa' => 'وضعیت یک شرکت‌کننده‌ی تماس را تغییر می‌دهد.', 'en' => 'Change a group-call participant\'s state.'],

    // --------------------------------------------------------------- stories
    'stories.sendStory' => ['fa' => 'یک استوری می‌فرستد.', 'en' => 'Send a story.'],
    'stories.editStory' => ['fa' => 'یک استوری را ویرایش می‌کند.', 'en' => 'Edit a story.'],
    'stories.deleteStories' => ['fa' => 'استوری‌ها را حذف می‌کند.', 'en' => 'Delete stories.'],
    'stories.getAllStories' => ['fa' => 'همه‌ی استوری‌ها را می‌گیرد.', 'en' => 'Get all stories.'],
    'stories.getStoriesByID' => ['fa' => 'استوری‌ها را با شناسه می‌گیرد.', 'en' => 'Get stories by id.'],
    'stories.getPeerStories' => ['fa' => 'استوری‌های یک peer را می‌گیرد.', 'en' => 'Get a peer\'s stories.'],
    'stories.incrementStoryViews' => ['fa' => 'شمارنده‌ی بازدید استوری را زیاد می‌کند.', 'en' => 'Increment story views.'],
    'stories.sendReaction' => ['fa' => 'روی یک استوری ری‌اکشن می‌گذارد.', 'en' => 'React to a story.'],
    'stories.getStoryViewsList' => ['fa' => 'فهرست بازدیدکنندگان استوری را می‌گیرد.', 'en' => 'Get the story viewers list.'],

    // --------------------------------------------------------------- premium
    'premium.getBoostsList' => ['fa' => 'فهرست بوست‌ها را می‌گیرد.', 'en' => 'Get the boosts list.'],
    'premium.applyBoost' => ['fa' => 'یک بوست را اعمال می‌کند.', 'en' => 'Apply a boost.'],
    'premium.getMyBoosts' => ['fa' => 'بوست‌های خودت را می‌گیرد.', 'en' => 'Get your own boosts.'],

    // ----------------------------------------------------------------- stats
    'stats.getBroadcastStats' => ['fa' => 'آمار یک کانال پخش را می‌گیرد.', 'en' => 'Get broadcast channel stats.'],
    'stats.getMegagroupStats' => ['fa' => 'آمار یک سوپرگروه را می‌گیرد.', 'en' => 'Get supergroup stats.'],
    'stats.getMessageStats' => ['fa' => 'آمار یک پیام را می‌گیرد.', 'en' => 'Get message stats.'],

    // ---------------------------------------------------------------- folders
    'folders.editPeerFolders' => ['fa' => 'پوشه‌های یک peer را ویرایش می‌کند.', 'en' => 'Edit a peer\'s folders.'],

    // -------------------------------------------------------------- chatlists
    'chatlists.exportChatlistInvite' => ['fa' => 'لینک دعوت یک چت‌لیست را می‌سازد.', 'en' => 'Create a chatlist invite link.'],
    'chatlists.joinChatlistInvite' => ['fa' => 'با لینک دعوت به یک چت‌لیست می‌پیوندد.', 'en' => 'Join a chatlist via an invite link.'],
    'chatlists.leaveChatlist' => ['fa' => 'از یک چت‌لیست خارج می‌شود.', 'en' => 'Leave a chatlist.'],

    // -------------------------------------------------------------- langpack
    'langpack.getLanguages' => ['fa' => 'زبان‌های موجود را می‌گیرد.', 'en' => 'Get available languages.'],
    'langpack.getLangPack' => ['fa' => 'یک بسته‌ی زبان را می‌گیرد.', 'en' => 'Get a language pack.'],
    'langpack.getStrings' => ['fa' => 'رشته‌های یک زبان را می‌گیرد.', 'en' => 'Get language strings.'],
    'langpack.getDifference' => ['fa' => 'تفاوت بسته‌ی زبان را می‌گیرد.', 'en' => 'Get language pack differences.'],

    // --------------------------------------------------------------- smsjobs
    'smsjobs.getStatus' => ['fa' => 'وضعیت SMS jobs را می‌گیرد.', 'en' => 'Get the SMS-jobs status.'],
    'smsjobs.join' => ['fa' => 'به SMS jobs می‌پیوندد.', 'en' => 'Join SMS jobs.'],
    'smsjobs.leave' => ['fa' => 'از SMS jobs خارج می‌شود.', 'en' => 'Leave SMS jobs.'],

    // -------------------------------------------------------------- ephemeral
    'ephemeral.sendMessage' => ['fa' => 'یک پیام ephemeral می‌فرستد.', 'en' => 'Send an ephemeral message.'],
    'ephemeral.editMessage' => ['fa' => 'یک پیام ephemeral را ویرایش می‌کند.', 'en' => 'Edit an ephemeral message.'],
    'ephemeral.deleteMessage' => ['fa' => 'یک پیام ephemeral را حذف می‌کند.', 'en' => 'Delete an ephemeral message.'],
    'ephemeral.getCallbackAnswer' => ['fa' => 'پاسخ callback یک پیام ephemeral را می‌گیرد.', 'en' => 'Get an ephemeral message callback answer.'],

    // -------------------------------------------------------------- aicompose
    'aicompose.createTone' => ['fa' => 'یک لحن (tone) جدید برای AI می‌سازد.', 'en' => 'Create a new AI tone.'],
    'aicompose.updateTone' => ['fa' => 'یک لحن AI را ویرایش می‌کند.', 'en' => 'Edit an AI tone.'],
    'aicompose.getTones' => ['fa' => 'لحن‌های AI را می‌گیرد.', 'en' => 'Get AI tones.'],

    // ------------------------------------------------------------ communities
    'communities.create' => ['fa' => 'یک انجمن (community) می‌سازد.', 'en' => 'Create a community.'],
    'communities.togglePeerLink' => ['fa' => 'پیوند یک peer به انجمن را تغییر می‌دهد.', 'en' => 'Toggle a peer\'s link to the community.'],
    'communities.toggleParticipantBanned' => ['fa' => 'بن شرکت‌کننده را تغییر می‌دهد.', 'en' => 'Toggle a participant\'s ban.'],
];
